spring:
  application:
    name: IS-project
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/is_app
  jpa:
    open-in-view: false
    properties:
      eclipselink.weaving: false
      eclipselink.default-schema: public
      eclipselink.logging.level: FINE
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    locations: classpath:db/migration
server:
  port: 8041
